name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Run unit tests
        run: |
          mkdir -p coverage
          ./node_modules/.bin/c8 \
            --reporter=text \
            --reporter=cobertura \
            node --test test/index.js

      - name: Run monkey tests
        run: node --test test/monkey.js

      - name: Run Flow
        run: ./node_modules/.bin/flow

      - name: Check TypeScript types with tsd
        run: ./node_modules/.bin/tsd src

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage
